Enhancement: AnyString and Empty
theflyingcodr/govalidator pull request #2
Opened 2021-10-13 10:53 UTC by Tigh-Gherr

Added AnyString func to check lists of strings without having to compile regex or define an inline func.

Added Empty func which just inverses NotEmpty.

Use IsZero for NotEmpty.

Added unit tests.

2021-10-13 14:30 UTC, theflyingcodr requested changes

2021-10-13 14:30 UTC, theflyingcodr commented on functions.go
> +// Empty will ensure that a value, val, is not empty.
Should this say ` Empty will ensure that a value, val, is empty.`

2021-10-13 15:03 UTC, tigh-latte commented on functions.go
> +// Empty will ensure that a value, val, is not empty.
So it should

2021-10-13 15:03 UTC, tigh-latte commented on functions.go
> +// Empty will ensure that a value, val, is not empty.
at's us nai

2021-11-08 12:08 UTC, theflyingcodr approved these changes
LGTM

2021-11-08 12:10 UTC, merged